name: cfn-lint

on:
  push:
    branches: [ main, develop, qa ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main, develop, qa ]

jobs:
  cloudformation-linter:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cfn-lint
        
    - name: Analysing the template with cfn-lint
      run: |
        cfn-lint --version
        cfn-lint ./role-test.yml
